Astrobotany project: Finding patterns from space data using statistical method

So far, from first milestone of the project, objective of the project(name of the project) was defined with help from Choi et.al paper. Then, data exploration was done with BRIC19 data by using R. Few of concerns and possible suggestions with data was discussed. Possible statistical method such as unsupervised learning(e.g. clustering) and deep learning(e.g. NLP based neural networks) was suggested.
After formal discussion with first milestone that I have done, it is decided that new data from NASA Gene lab GLDS-120 will be used to perform the analysis. Therefore, process that was done with first mileston, such as, data preprocessing and data exploration will be performed again before building the main model. This time Python will be used for the analysis.

Study Description of GLDS-120: 

Experimentation on the International Space Station has reached the stage where repeated and nuanced transcriptome studies are beginning to illuminate the **structural and metabolic differences between plants grown in space compared to plants on the Earth.** 

Genes that are important in setting up the spaceflight responses are being identified; their role in spaceflight physiological adaptation are increasingly understood, and the fact that different genotypes adapt differently is recognized. However, the basic question of whether these spaceflight responses are required for survival has yet to be posed, and the fundamental notion that spaceflight responses may be non-adaptive has yet to be explored.
Therefore the experiments presented here were designed to ask **if portions of the plant spaceflight response can be genetically removed without causing loss of spaceflight survival and without causing increased stress responses.**

The CARA experiment compared the spaceflight transcriptome responses of two Arabidopsis ecotypes, Col-0 and WS, as well as that of a PhyD mutant of Col-0. When grown with the ambient light of the ISS, phyD displayed a significantly reduced spaceflight transcriptome response compared to Col-0, **suggesting that altering the activity of a single gene can actually improve spaceflight adaptation by reducing the transcriptome cost of physiological adaptation.** The WS genotype showed an even simpler spaceflight transcriptome response in the ambient light of the ISS, more **broadly indicating that the plant genotype can be manipulated to reduce the transcriptome cost of plant physiological adaptation to spaceflight and suggesting that genetic manipulation might further reduce, or perhaps eliminate the metabolic cost of spaceflight adaptation.** 

When plants were germinated and then left in the dark on the ISS, the WS genotype actually mounted a larger transcriptome response than Col-0, suggesting that the in-space light environment affects physiological adaptation, which further **implies that manipulating the local habitat can also substantially impact the metabolic cost of spaceflight adaptation**.

'Normalized_counts' data from GLDS-120 will be mainly used and  'Array_Genediff_pilot','RNAseq_Genediff_pilot' and 'RNAseq_Isoformsdiff_pilot' will be used as supplemantary data.

Objective of this project will be remained same:
Finding patterns from space data using statistical method

In [1]:
%load_ext watermark
%watermark -a 'Alex-Seo' -v -p matplotlib,numpy,pandas

Alex-Seo

CPython 3.6.2
IPython 6.1.0

matplotlib 3.2.0
numpy 1.18.1
pandas 1.0.1

In [3]:
#Data Exploration
import pandas as pd
import numpy as np
import random as rnd

# visualization
import altair as alt
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
nc_all = pd.read_csv("GLDS-120_rna_seq_Normalized_Counts.csv")

In [5]:
#Summary
nc_all.head()
#print(nc_all.columns.values)
#nc_all.describe(include='all')

,RNA_seq,Atha_Col-0-PhyD_root_FLT_Alight_Rep1_GSM2493783,Atha_Col-0-PhyD_root_FLT_Alight_Rep2_GSM2493784,Atha_Col-0-PhyD_root_FLT_Alight_Rep3_GSM2493785,Atha_Col-0-PhyD_root_FLT_dark_Rep1_GSM2493792,Atha_Col-0-PhyD_root_FLT_dark_Rep2_GSM2493793,Atha_Col-0-PhyD_root_FLT_dark_Rep3_GSM2493794,Atha_Col-0-PhyD_root_GC_Alight_Rep1_GSM2493765,Atha_Col-0-PhyD_root_GC_Alight_Rep2_GSM2493766,Atha_Col-0-PhyD_root_GC_Alight_Rep3_GSM2493767,...,Atha_Ws_root_FLT_Alight_Rep3_GSM2493782,Atha_Ws_root_FLT_dark_Rep1_GSM2493789,Atha_Ws_root_FLT_dark_Rep2_GSM2493790,Atha_Ws_root_FLT_dark_Rep3_GSM2493791,Atha_Ws_root_GC_Alight_Rep1_GSM2493762,Atha_Ws_root_GC_Alight_Rep2_GSM2493763,Atha_Ws_root_GC_Alight_Rep3_GSM2493764,Atha_Ws_root_GC_dark_Rep1_GSM2493771,Atha_Ws_root_GC_dark_Rep2_GSM2493772,Atha_Ws_root_GC_dark_Rep3_GSM2493773
0,AT1G01010,116.888298,132.379479,212.743795,182.011159,37.451300,36.191007,97.652423,193.262178,105.192824,...,88.250619,53.594919,139.944149,149.854946,62.133158,109.261341,80.132301,21.675591,69.483039,115.772776
1,AT1G01020,309.753663,275.664706,271.519734,270.261115,369.703512,323.787491,321.676426,235.522120,331.126841,...,242.874452,212.480431,247.649370,193.853179,277.896901,235.501416,250.294311,217.427950,233.272214,244.534539
2,AT1G01030,15.605457,31.582754,33.380759,39.331565,66.818571,114.980428,40.688977,79.069498,69.055665,...,43.629223,17.030337,48.459228,63.638014,33.698318,58.330341,33.802204,48.068188,25.012820,34.297481
3,AT1G01040,87.827413,66.439742,59.069120,65.637198,118.481842,83.514259,91.966383,101.624349,58.173340,...,119.232764,123.953587,118.829533,163.138572,119.058956,76.548721,116.494389,97.803263,132.859933,151.702383
4,AT1G01050,1381.723141,1260.158962,1304.779193,1286.505645,940.910219,1425.881579,1121.849300,1727.003728,1415.289380,...,1545.700537,1241.428582,1111.929045,868.365582,1132.979712,1181.454980,1323.852859,1492.290175,1205.715025,966.320255

In [6]:
###Data reconstruction, Make more variables and set the output(Y) variable
###You can not use melt() from pandas since there are 3 rep for each segment

###replicate each row 12 times for same RNA_seq
newnc = pd.DataFrame(np.repeat(nc_all.values,12,axis=0))
#newnc.colums = nc_all.columns

###Create Genotype variable
GT = pd.DataFrame(
{"Genotype" : ['phyD', 'phyD', 'phyD', 'phyD',
               'col0', 'col0','col0','col0',
               'WS', 'WS', 'WS', 'WS']})
GT = pd.concat([GT]*len(nc_all)).reset_index().drop(columns=['index'])

###Create Light setting variable

LS = pd.DataFrame(
{"Light_Setting" : ['Light' ,'Dark']})
LS = pd.concat([LS]*6*len(nc_all)).reset_index().drop(columns=['index'])

###create Location variable
LC = pd.DataFrame(
{"Location" : ['FLT' ,'FLT', 'GC', 'GC']})
LC = pd.concat([LC]*3*len(nc_all)).reset_index().drop(columns=['index'])

###Transpose fpkm values (3 values)
ncworna = nc_all.drop(columns = ['RNA_seq'])
D = pd.DataFrame(columns=['Rep1', 'Rep2', 'Rep3'])

for i in range(len(ncworna)):
    s = pd.Series(ncworna.iloc[i]) #Make each row a pandas series
    a = np.reshape(s.to_numpy(),(12,3)) #Change Series to numpy and reshape it
    #Make each reshaped arrays into dataframe, this one dataframe represent one RNA sequence
    d = pd.DataFrame(a, columns=['Rep1', 'Rep2', 'Rep3'])
    D = pd.concat([D,d]) #concat each dataframe

D = D.reset_index().drop(columns=['index'])#Reset index
###Add and drop variables
newnc = newnc.drop(columns=range(1,37))

newnc["Genotype"] = GT
newnc["Light_Setting"] = LS

newnc = pd.concat([newnc, D], axis = 1)

newnc["Location"] = LC

#Rename column
newnc = newnc.rename(columns = {0 : "RNA_seq"})
#Overview of newly constructed dataset
newnc.head()

,RNA_seq,Genotype,Light_Setting,Rep1,Rep2,Rep3,Location
0,AT1G01010,phyD,Light,116.888298,132.379479,212.743795,FLT
1,AT1G01010,phyD,Dark,182.011159,37.451300,36.191007,FLT
2,AT1G01010,phyD,Light,97.652423,193.262178,105.192824,GC
3,AT1G01010,phyD,Dark,154.933696,88.312487,136.879249,GC
4,AT1G01010,col0,Light,119.461406,116.426029,140.074158,FLT

In [7]:
#Applying models using newly constructed labeled dataset

#Label Encoding - One hot encoding on categorical predictors for modeling purpose
ncwd = pd.get_dummies(newnc, columns = ["Genotype"]) #drop_first =True
ncwd = pd.get_dummies(ncwd, columns = ['Light_Setting'])

clean_target = {"Location": {"FLT": 1, "GC": 0}}
ncwd.replace(clean_target, inplace = True)

ncwd.head()

,RNA_seq,Rep1,Rep2,Rep3,Location,Genotype_WS,Genotype_col0,Genotype_phyD,Light_Setting_Dark,Light_Setting_Light
0,AT1G01010,116.888298,132.379479,212.743795,1,0,0,1,0,1
1,AT1G01010,182.011159,37.451300,36.191007,1,0,0,1,1,0
2,AT1G01010,97.652423,193.262178,105.192824,0,0,0,1,0,1
3,AT1G01010,154.933696,88.312487,136.879249,0,0,0,1,1,0
4,AT1G01010,119.461406,116.426029,140.074158,1,0,1,0,0,1

In [8]:
#Pacakages
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier

C:\Users\LG\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

In [9]:
#Model 1 - Start with a basics: Since the target variables are binary, Apply Logistic Regression for classification

#Shuffle, then divide it into training and test dataset
y = ncwd['Location'].values
X = ncwd.iloc[:, [1,2,3,5,6,7,8,9]].values
#Shuffle
indices = np.arange(X.shape[0])
rng = np.random.RandomState(123)
permuted_indices = rng.permutation(indices)
#Split - 80(Train) : 20(Test)
train_size = int(0.8*X.shape[0])
test_size = X.shape[0] - (train_size)
print(train_size, test_size)

train_ind = permuted_indices[:train_size]
test_ind = permuted_indices[train_size:]

X_train, y_train = X[train_ind], y[train_ind]
X_test, y_test = X[test_ind], y[test_ind]

X_train.shape

## No more preprocessing needed such as, scaling and normalization. - else use pipelines form sckitlearn
## All features, Genotype, Lightsetting and fpkm shouldn't be modified in anyways since first two are categorical variables
## and fpkm values have meanings itself

230265 57567

(230265, 8)

In [10]:
#Logistic Regression

logreg = LogisticRegression()
logreg.fit(X_train, y_train)
#y_pred = logreg.predict(X_test)
acc_log = round(logreg.score(X_test, y_test) * 100, 2)
print(acc_log)

50.19

In [ ]:
#Additional Machine Learning Models
#SVM
#Takes toooo much time to compile
svc = SVC()
svc.fit(X_train, y_train)
#y_pred = svc.predict(X_test)
acc_svc = round(svc.score(X_test, y_test) * 100, 2)
print(acc_svc)

In [11]:
#KNN

knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train, y_train)
#y_pred = knn.predict(X_test)
acc_knn = round(knn.score(X_test, y_test) * 100, 2)
print(acc_knn)

56.35

In [13]:
# Random Forest

random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train, y_train)
#y_pred = random_forest.predict(X_test)
acc_random_forest = round(random_forest.score(X_test, y_test) * 100, 2)
print(acc_random_forest)

70.07